# Generated by Django 5.0.1 on 2024-02-19 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Childs', '0002_foundchilds_approval_status_and_more'),
        ('Home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundchilds',
            name='Photo_Of_Child',
            field=models.FileField(upload_to='Found_Childs'),
        ),
        migrations.CreateModel(
            name='PoliceCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=255)),
                ('District', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('FIR_Status', models.CharField(max_length=255, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('Insident_Date', models.DateField()),
                ('Compliant', models.CharField(max_length=2000)),
                ('closingdate', models.DateField(null=True)),
                ('PoliceStation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.policedata')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
