# Generated by Django 5.0.1 on 2024-02-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Childs', '0003_alter_foundchilds_photo_of_child_policecase'),
    ]

    operations = [
        migrations.AddField(
            model_name='policecase',
            name='approval_status',
            field=models.BooleanField(default=False),
        ),
    ]
